# Generated by Django 4.1.1 on 2023-03-08 10:56

import APIfull.custom_valid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIfull', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[APIfull.custom_valid.No_equal_to(0)])),
                ('length', models.FloatField(validators=[APIfull.custom_valid.No_equal_to(0)])),
                ('height', models.FloatField(validators=[APIfull.custom_valid.No_equal_to(0)])),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=21)),
                ('lifeStatus', models.CharField(blank=True, choices=[('ALIVE', 'ALIVE'), ('DEAD', 'DEAD')], default='ALIVE', max_length=21)),
                ('chippingDateTime', models.DateTimeField(auto_now_add=True)),
                ('deathDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalsLocationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeOfVisitLocationPoint', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=140, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[APIfull.custom_valid.locations_validate(90)])),
                ('longitude', models.FloatField(validators=[APIfull.custom_valid.locations_validate(180)])),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='firstName',
            field=models.CharField(max_length=140, verbose_name='firstName'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lastName',
            field=models.CharField(max_length=140, verbose_name='lastName'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=140, verbose_name='пароль'),
        ),
        migrations.CreateModel(
            name='visitedLocationsM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIfull.animals')),
                ('AnimalsLocationVisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIfull.animalslocationvisit')),
            ],
        ),
        migrations.AddField(
            model_name='animalslocationvisit',
            name='locationPointId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIfull.locations'),
        ),
        migrations.AddField(
            model_name='animals',
            name='animalTypes',
            field=models.ManyToManyField(related_name='animalTypes_list', to='APIfull.animalstype'),
        ),
        migrations.AddField(
            model_name='animals',
            name='chipperId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chipperID', to='APIfull.myuser'),
        ),
        migrations.AddField(
            model_name='animals',
            name='chippingLocationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chippingLocationId_list', to='APIfull.locations'),
        ),
        migrations.AddField(
            model_name='animals',
            name='visitedLocations',
            field=models.ManyToManyField(blank=True, related_name='visitedLocations', through='APIfull.visitedLocationsM2M', to='APIfull.animalslocationvisit'),
        ),
    ]
